import {
  ChessRook,
  ChessPawn,
  ChessQueen,
  ChessBishop,
  ChessKnight,
  ChevronsLeft,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronFirst,
  ChevronLast,
  Copy,
  Check,
  Settings,
  Flag,
  RotateCcw,
  Plus,
  Play,
  Pause,
  Upload,
  Square,
  FileText,
  X,
  User,
  Bot,
  Sun,
  Moon,
  Monitor,
  ArrowUpDown,
  Ban,
  Share2,
  Eye,
  EyeOff,
  Brain,
  Edit,
  Trash2,
  Crown,
  Volume2,
  VolumeX,
  Eraser,
  RotateCw,
  Download,
  Undo2,
  Redo2,
  Shuffle,
  ArrowUpRight,
  ArrowRight,
  Cpu,
  Users,
  Microscope,
  CircleStar,
  Menu,
  Maximize2,
  Minimize2,
  Loader2,
  Zap,
  Rabbit,
  Turtle,
  FlipVertical,
  Puzzle,
  Heart,
  Clock,
  BookOpen,
  Target,
  type LucideIcon
} from 'lucide-react';

export const Icons = {
  chessPawn: ChessPawn,
  chessKnight: ChessKnight,
  chessBishop: ChessBishop,
  chessRook: ChessRook,
  chessQueen: ChessQueen,
  chessKing: Crown,

  chevronsLeft: ChevronsLeft,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsRight: ChevronsRight,
  chevronFirst: ChevronFirst,
  chevronLast: ChevronLast,

  copy: Copy,
  check: Check,
  settings: Settings,
  flag: Flag,
  rematch: RotateCcw,
  newGame: Plus,
  flipBoard: ArrowUpDown,
  share: Share2,
  play: Play,
  pause: Pause,
  upload: Upload,
  download: Download,
  square: Square,
  close: X,
  fileText: FileText,
  edit: Edit,
  trash: Trash2,
  eraser: Eraser,
  undo: Undo2,
  redo: Redo2,
  shuffle: Shuffle,
  rotate: RotateCw,

  player: User,
  stockfish: Bot,

  sun: Sun,
  moon: Moon,
  system: Monitor,
  abort: Ban,

  analyze: Eye,
  analyzeOff: EyeOff,
  engine: Brain,

  volumeOn: Volume2,
  volumeOff: VolumeX,

  fullscreen: Maximize2,
  exitFullscreen: Minimize2,

  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  cpu: Cpu,
  users: Users,
  microscope: Microscope,
  circlestar: CircleStar,
  menu: Menu,
  crown: Crown,
  spinner: Loader2,
  zap: Zap,
  rabbit: Rabbit,
  turtle: Turtle,
  flipVertical: FlipVertical,
  puzzle: Puzzle,
  heart: Heart,
  clock: Clock,
  book: BookOpen,
  target: Target
} as const;

export type { LucideIcon };
