# syntax=docker.io/docker/dockerfile:1

FROM node:26-alpine

RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

WORKDIR /app

COPY prisma ./prisma

COPY package.json pnpm-lock.yaml* .npmrc* ./
RUN pnpm i --frozen-lockfile --ignore-scripts

RUN pnpm prisma generate

COPY . .

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=development

CMD ["sh", "-c", "pnpm prisma migrate deploy && pnpm dev"]