FROM oven/bun:1 AS install
WORKDIR /temp

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

FROM oven/bun:1 AS release
WORKDIR /usr/src/app

COPY --from=install /temp/node_modules node_modules
COPY . .

ARG PORT=8080
EXPOSE $PORT

USER bun
ENTRYPOINT ["bun", "server.ts"]